In [41]:
import pandas as pd
import numpy as np

In [42]:
crime_anal_police = pd.read_csv('CCTV/02. crime_in_Seoul.csv',
           thousands=',',
           encoding='euc-kr'
           )

In [43]:
crime_anal_police.head()

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
0   중부서      2      2      3      2    105     65   1395    477   1355   1170
1   종로서      3      3      6      5    115     98   1070    413   1278   1070
2  남대문서      1      0      6      4     65     46   1153    382    869    794
3  서대문서      2      2      5      4    154    124   1812    738   2056   1711
4   혜화서      3      2      5      4     96     63   1114    424   1015    861

In [44]:
!pip install googlemaps

Requirement already satisfied: googlemaps in c:\programdata\anaconda3\lib\site-packages (4.4.1)
Requirement already satisfied: requests<3.0,>=2.20.0 in c:\programdata\anaconda3\lib\site-packages (from googlemaps) (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (1.24.2)
Requirement already satisfied: idna<2.9,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2019.9.11)

In [45]:
import googlemaps

In [46]:
gmaps_keys = 'AIzaSyAi6n44kks_267rNMtkekzwdHAxwnHbyPQ'
gmaps = googlemaps.Client(key=gmaps_keys)

In [47]:
gmaps.geocode('서울중부경찰서', language='ko')

[{'address_components': [{'long_name': '２７',
    'short_name': '２７',
    'types': ['premise']},
   {'long_name': '수표로',
    'short_name': '수표로',
    'types': ['political', 'sublocality', 'sublocality_level_4']},
   {'long_name': '을지로동',
    'short_name': '을지로동',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '중구',
    'short_name': '중구',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '100-032',
    'short_name': '100-032',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 서울특별시 중구 을지로동 수표로 27',
  'geometry': {'location': {'lat': 37.5636465, 'lng': 126.9895796},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 37.56499548029149,
     'lng': 126.9909285802915},
    'southwest': {'lat': 37.56229751970849, 'lng': 126.9882306197085}}},
  'place_id': 'ChIJc-9q5uSifDURLhQmr5wkXmc',
  'plus_code': {'compound_code': 'HX7Q+FR 대한민국 서울특별시',
   'global_code': '8Q98HX7Q+FR'},
  'types': ['establishment', 'point_of_interest', 'police']}]

In [48]:
gmaps.geocode('신촌역', language='ko')

[{'address_components': [{'long_name': '신촌',
    'short_name': '신촌',
    'types': ['establishment',
     'point_of_interest',
     'subway_station',
     'transit_station']},
   {'long_name': '신촌동',
    'short_name': '신촌동',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '120-140',
    'short_name': '120-140',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 서울특별시 신촌동 신촌',
  'geometry': {'location': {'lat': 37.559778, 'lng': 126.942325},
   'location_type': 'GEOMETRIC_CENTER',
   'viewport': {'northeast': {'lat': 37.5611269802915,
     'lng': 126.9436739802915},
    'southwest': {'lat': 37.55842901970851, 'lng': 126.9409760197085}}},
  'place_id': 'ChIJ0RGmEpCYfDURAziCwM4_WcU',
  'plus_code': {'compound_code': 'HW5R+WW 대한민국 서울특별시',
   'global_code': '8Q98HW5R+WW'},
  'types': ['establishment',
   'point_of_interest',
   'subway_station',
   'transit_station']},
 {'address_components': [{'long_name': '신촌역2호선',
    'short_name': '신촌역2호선',
    'types': ['establishment', 'point_of_interest', 'transit_station']},
   {'long_name': '신촌동',
    'short_name': '신촌동',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '120-180',
    'short_name': '120-180',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 서울특별시 신촌동 신촌역2호선',
  'geometry': {'location': {'lat': 37.5562944, 'lng': 126.9399855},
   'location_type': 'GEOMETRIC_CENTER',
   'viewport': {'northeast': {'lat': 37.55764338029149,
     'lng': 126.9413344802915},
    'southwest': {'lat': 37.5549454197085, 'lng': 126.9386365197085}}},
  'place_id': 'ChIJ8SSo3JaYfDURkfjQoKuHBmE',
  'plus_code': {'compound_code': 'HW4Q+GX 대한민국 서울특별시',
   'global_code': '8Q98HW4Q+GX'},
  'types': ['establishment', 'point_of_interest', 'transit_station']}]

In [49]:
gmaps.geocode('더조은 컴퓨터 아카데미 신촌점', language='ko')

[{'address_components': [{'long_name': '마포구',
    'short_name': '마포구',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': '노고산동',
    'short_name': '노고산동',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '121-100',
    'short_name': '121-100',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 서울특별시 마포구 노고산동 57-1',
  'geometry': {'location': {'lat': 37.5549035, 'lng': 126.9360342},
   'location_type': 'GEOMETRIC_CENTER',
   'viewport': {'northeast': {'lat': 37.5562524802915,
     'lng': 126.9373831802915},
    'southwest': {'lat': 37.55355451970851, 'lng': 126.9346852197085}}},
  'place_id': 'ChIJ4XNdl5WYfDURLSD0rRqSVWI',
  'plus_code': {'compound_code': 'HW3P+XC 대한민국 서울특별시',
   'global_code': '8Q98HW3P+XC'},
  'types': ['establishment', 'point_of_interest']}]

### 1. 관서명을 가져온다.
### 2. 뒤에 '서'를 제거한다. (name[:-1] - 맨 앞에서 끝 -1(전)까지)
### 3. 앞에 '서울' / 뒤에 '경찰서'를 붙인다.
### 4. 만들어진 관서명으로 위도 경도를 가져온다.

In [50]:
station_name = []

for name in crime_anal_police['관서명']:
    station_name.append('서울' + name[:-1] + '경찰서')
    
station_name

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

- 각 경찰서 별 전체 주소 리스트
- 각 경찰서 별 위도 리스트
- 각 경찰서 별 경도 리스트

In [51]:
station_address = [] # 주소
station_lat = [] # 위도
station_lng = [] # 경도

for name in station_name:
    tmp = gmaps.geocode(name, language='ko')
    station_address.append(tmp[0].get('formatted_address'))
    
    tmp_loc = tmp[0].get('geometry')
    station_lat.append(tmp_loc['location']['lat'])
    station_lng.append(tmp_loc['location']['lng'])
    
    print(name + '  -->  ' + tmp[0].get('formatted_address') 
          + "  위도" + str(tmp_loc['location']['lat'])
          + "  경도" + str(tmp_loc['location']['lng']))

서울중부경찰서  -->  대한민국 서울특별시 중구 을지로동 수표로 27  위도37.5636465  경도126.9895796
서울종로경찰서  -->  대한민국 서울특별시 종로구 종로1.2.3.4가동 율곡로 46  위도37.5755578  경도126.9848674
서울남대문경찰서  -->  대한민국 서울특별시 중구 회현동 한강대로 410  위도37.5547584  경도126.9734981
서울서대문경찰서  -->  대한민국 서울특별시 서대문구 충현동 통일로 113  위도37.5647848  경도126.9667762
서울혜화경찰서  -->  대한민국 서울특별시 종로구 인의동 창경궁로 112-16  위도37.5718529  경도126.9989143
서울용산경찰서  -->  대한민국 서울특별시 용산구 원효로1가 백범로 329  위도37.5387099  경도126.9659183
서울성북경찰서  -->  대한민국 서울특별시 성북구 삼선동5가 301  위도37.5897482  경도127.0161353
서울동대문경찰서  -->  대한민국 서울특별시 동대문구 청량리동 약령시로21길 29  위도37.58506149999999  경도127.0457679
서울마포경찰서  -->  대한민국 서울특별시 마포구 아현동 마포대로 183  위도37.550814  경도126.954028
서울영등포경찰서  -->  대한민국 서울특별시 영등포구 영등포동1가 618-7  위도37.5153176  경도126.905728
서울성동경찰서  -->  대한민국 서울특별시 성동구 행당동 왕십리광장로 9  위도37.5617309  경도127.0363806
서울동작경찰서  -->  대한민국 서울특별시 동작구 노량진1동 노량진로 148  위도37.5130866  경도126.9428498
서울광진경찰서  -->  대한민국 서울특별시 광진구 구의동 자양로 167  위도37.542873  경도127.083821
서울서부경찰서  -->  대한민국 서울특별시 은평구 신사2동 184-56  위도37.591836  경도126.9053648
서울강북경찰서  -->  대한민국 서울특별시 강북구 번1동 오패산로 406  위도37.63730390000001  경도127.0273399
서울금천경찰서  -->  대한민국 서울특별시 금천구 시흥동 190  위도37.4568722  경도126.8970429
서울중랑경찰서  -->  대한민국 서울특별시 중랑구 망우동 489-7  위도37.5990885  경도127.0956516
서울강남경찰서  -->  대한민국 서울특별시 강남구 대치동 998  위도37.5094352  경도127.0669578
서울관악경찰서  -->  대한민국 서울특별시 관악구 봉천동  위도37.4743789  경도126.9509748
서울강서경찰서  -->  대한민국 서울특별시 강서구 화곡6동 980-15  위도37.5516732  경도126.8499269
서울강동경찰서  -->  대한민국 서울특별시 강동구 성내1동 성내로 57  위도37.528511  경도127.1268224
서울종암경찰서  -->  대한민국 서울특별시 성북구 종암동 종암로 135  위도37.6020592  경도127.0321577
서울구로경찰서  -->  대한민국 서울특별시 구로구 구로동 가마산로 235  위도37.494931  경도126.886731
서울서초경찰서  -->  대한민국 서울특별시 서초구 서초3동 반포대로 179  위도37.4956054  경도127.0052504
서울양천경찰서  -->  대한민국 서울특별시 양천구 신정6동 목동동로 99  위도37.5165667  경도126.8656763
서울송파경찰서  -->  대한민국 서울특별시 송파구 가락본동 9  위도37.5019065  경도127.1271513
서울노원경찰서  -->  대한민국 서울특별시 노원구 하계동 노원로 283  위도37.6425238  경도127.0717076
서울방배경찰서  -->  대한민국 서울특별시 서초구 방배본동 동작대로 204  위도37.4945959  경도126.9831279
서울은평경찰서  -->  대한민국 서울특별시 은평구 불광동 연서로 365  위도37.6283597  경도126.9287226
서울도봉경찰서  -->  대한민국 서울특별시 도봉구 창4동 노해로 403  위도37.6533589  경도127.052682
서울수서경찰서  -->  대한민국 서울특별시 강남구 개포동 개포로 617  위도37.49349  경도127.0772119

In [52]:
station_lat

[37.5636465,
 37.5755578,
 37.5547584,
 37.5647848,
 37.5718529,
 37.5387099,
 37.5897482,
 37.58506149999999,
 37.550814,
 37.5153176,
 37.5617309,
 37.5130866,
 37.542873,
 37.591836,
 37.63730390000001,
 37.4568722,
 37.5990885,
 37.5094352,
 37.4743789,
 37.5516732,
 37.528511,
 37.6020592,
 37.494931,
 37.4956054,
 37.5165667,
 37.5019065,
 37.6425238,
 37.4945959,
 37.6283597,
 37.6533589,
 37.49349]

In [53]:
station_lng

[126.9895796,
 126.9848674,
 126.9734981,
 126.9667762,
 126.9989143,
 126.9659183,
 127.0161353,
 127.0457679,
 126.954028,
 126.905728,
 127.0363806,
 126.9428498,
 127.083821,
 126.9053648,
 127.0273399,
 126.8970429,
 127.0956516,
 127.0669578,
 126.9509748,
 126.8499269,
 127.1268224,
 127.0321577,
 126.886731,
 127.0052504,
 126.8656763,
 127.1271513,
 127.0717076,
 126.9831279,
 126.9287226,
 127.052682,
 127.0772119]

In [54]:
gu_name = []

for name in station_address:
    tmp = name.split()
    for x in tmp:
        if(x[-1] == '구'):
            gu_name.append(x)
            
gu_name

# 구 이름을 빼내는 두가지 방법

- 1

In [58]:
gu_name1 = []

for name in station_address:
    tmp = name.split()
    for x in tmp:
        if(x[-1] == '구'):
            gu_name1.append(x)
            
gu_name1

['중구',
 '종로구',
 '중구',
 '서대문구',
 '종로구',
 '용산구',
 '성북구',
 '동대문구',
 '마포구',
 '영등포구',
 '성동구',
 '동작구',
 '광진구',
 '은평구',
 '강북구',
 '금천구',
 '중랑구',
 '강남구',
 '관악구',
 '강서구',
 '강동구',
 '성북구',
 '구로구',
 '서초구',
 '양천구',
 '송파구',
 '노원구',
 '서초구',
 '은평구',
 '도봉구',
 '강남구']

- 2

In [56]:
gu_name2 = []

for name in station_address:
    tmp = name.split()
    tmp_gu = [x for x in tmp if x[-1] == '구'][0]
    gu_name2.append(tmp_gu)
    print(gu_name2)
gu_name2

['중구']
['중구', '종로구']
['중구', '종로구', '중구']
['중구', '종로구', '중구', '서대문구']
['중구', '종로구', '중구', '서대문구', '종로구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구', '서초구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구', '서초구', '양천구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구', '서초구', '양천구', '송파구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구', '서초구', '양천구', '송파구', '노원구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구', '서초구', '양천구', '송파구', '노원구', '서초구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구', '서초구', '양천구', '송파구', '노원구', '서초구', '은평구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구', '서초구', '양천구', '송파구', '노원구', '서초구', '은평구', '도봉구']
['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '강서구', '강동구', '성북구', '구로구', '서초구', '양천구', '송파구', '노원구', '서초구', '은평구', '도봉구', '강남구']

['중구',
 '종로구',
 '중구',
 '서대문구',
 '종로구',
 '용산구',
 '성북구',
 '동대문구',
 '마포구',
 '영등포구',
 '성동구',
 '동작구',
 '광진구',
 '은평구',
 '강북구',
 '금천구',
 '중랑구',
 '강남구',
 '관악구',
 '강서구',
 '강동구',
 '성북구',
 '구로구',
 '서초구',
 '양천구',
 '송파구',
 '노원구',
 '서초구',
 '은평구',
 '도봉구',
 '강남구']

In [60]:
crime_anal_police['구별'] = gu_name

In [61]:
crime_anal_police.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [62]:
crime_anal_police.to_csv('CCTV/02. crime_in_Seoul_include_gu_name_.csv', sep=',', encoding='utf-8')

In [63]:
crime_anal_raw = pd.read_csv('CCTV/02. crime_in_Seoul_include_gu_name.csv', encoding='utf-8')

In [65]:
crime_anal_raw.head()

,Unnamed: 0,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

### pivot = 요약(summary)

#### aggfunc에서 합, 평균, 분산 등 np에서 사용할 수 있는 함수를 사용할 수 있다.

In [66]:
crime_anal = pd.pivot_table(crime_anal_raw, index='구별', aggfunc=np.sum)
crime_anal.head()

,Unnamed: 0,강간 검거,강간 발생,강도 검거,강도 발생,살인 검거,살인 발생,절도 검거,절도 발생,폭력 검거,폭력 발생
구별,,,,,,,,,,,
강남구,47,349,449,18,21,10,13,1650,3850,3705,4284
강동구,20,123,156,8,6,3,4,789,2366,2248,2712
강북구,14,126,153,13,14,8,7,618,1434,2348,2649
강서구,19,191,262,13,13,8,7,1260,2096,2718,3207
관악구,18,221,320,14,12,8,9,827,2706,2642,3298

In [67]:
crime_anal['강간검거율'] = crime_anal['강간 검거']/crime_anal['강간 발생']*100
crime_anal['강도검거율'] = crime_anal['강도 검거']/crime_anal['강도 발생']*100
crime_anal['살인검거율'] = crime_anal['살인 검거']/crime_anal['살인 발생']*100
crime_anal['절도검거율'] = crime_anal['절도 검거']/crime_anal['절도 발생']*100
crime_anal['폭력검거율'] = crime_anal['폭력 검거']/crime_anal['폭력 발생']*100

In [70]:
crime_anal.head()

,Unnamed: 0,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,
강남구,47,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,20,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,14,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
강서구,19,262,13,7,2096,3207,72.900763,100.000000,114.285714,60.114504,84.752105
관악구,18,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157

In [69]:
del crime_anal['강간 검거']
del crime_anal['강도 검거']
del crime_anal['살인 검거']
del crime_anal['절도 검거']
del crime_anal['폭력 검거']

In [71]:
con_list = ['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']

for column in con_list:
       crime_anal.loc[crime_anal[column] > 100, column] = 100

In [72]:
crime_anal.head()

,Unnamed: 0,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,
강남구,47,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,20,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,14,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
강서구,19,262,13,7,2096,3207,72.900763,100.000000,100.000000,60.114504,84.752105
관악구,18,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157

In [73]:
crime_anal.rename(columns={'강간 발생' : '강간',
                          '강도 발생' : '강도',
                          '살인 발생' : '살인',
                          '절도 발생' : '절도',
                          '폭력 발생' : '폭력',
                          }, inplace=True)

In [75]:
crime_anal

,Unnamed: 0,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,
강남구,47,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,20,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,14,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
강서구,19,262,13,7,2096,3207,72.900763,100.000000,100.000000,60.114504,84.752105
관악구,18,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,12,240,14,4,3026,2625,91.666667,100.000000,100.000000,42.200925,83.047619
구로구,22,281,15,8,2335,3007,58.362989,73.333333,75.000000,38.072805,80.877951
금천구,15,151,6,3,1567,2054,80.794702,100.000000,100.000000,56.668794,86.465433
노원구,26,197,7,10,2193,2723,61.421320,100.000000,100.000000,36.525308,85.530665
도봉구,29,102,9,3,1063,1487,100.000000,100.000000,100.000000,44.967074,87.626093
동대문구,7,173,13,5,1981,2548,84.393064,100.000000,100.000000,41.090358,87.401884
동작구,11,285,9,5,1865,1910,48.771930,55.555556,100.000000,35.442359,83.089005
마포구,8,294,14,8,2555,2983,84.013605,71.428571,100.000000,31.819961,84.445189
서대문구,3,154,5,2,1812,2056,80.519481,80.000000,100.000000,40.728477,83.219844
서초구,50,393,9,8,2635,2399,63.358779,66.666667,75.000000,41.404175,87.453105
성동구,10,126,9,4,1607,1612,94.444444,88.888889,100.000000,37.149969,86.538462
성북구,27,150,5,5,1785,2209,82.666667,80.000000,100.000000,41.512605,83.974649
송파구,25,220,13,11,3239,3295,80.909091,76.923077,90.909091,34.856437,84.552352
양천구,24,120,6,3,1890,2509,87.500000,50.000000,100.000000,35.555556,80.908729
영등포구,9,295,22,14,2964,3572,62.033898,90.909091,85.714286,32.995951,82.894737
용산구,5,194,14,5,1557,2050,89.175258,100.000000,100.000000,37.700706,83.121951
은평구,41,166,9,3,1914,2653,84.939759,66.666667,100.000000,37.147335,86.920467
종로구,5,211,11,6,2184,2293,76.303318,81.818182,83.333333,38.324176,84.212822
중구,2,170,9,3,2548,2224,65.294118,66.666667,66.666667,33.712716,88.309353
중랑구,16,187,11,13,2135,2847,79.144385,81.818182,92.307692,38.829040,84.545135